/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddVmToVpcDto
 */
export interface AddVmToVpcDto {
    /**
     * The ID of the VM
     * @type {string}
     * @memberof AddVmToVpcDto
     */
    vmId: string;
    /**
     * The ID of the VPC
     * @type {string}
     * @memberof AddVmToVpcDto
     */
    vpcId: string;
}

/**
 * Check if a given object implements the AddVmToVpcDto interface.
 */
export function instanceOfAddVmToVpcDto(value: object): value is AddVmToVpcDto {
    if (!('vmId' in value) || value['vmId'] === undefined) return false;
    if (!('vpcId' in value) || value['vpcId'] === undefined) return false;
    return true;
}

export function AddVmToVpcDtoFromJSON(json: any): AddVmToVpcDto {
    return AddVmToVpcDtoFromJSONTyped(json, false);
}

export function AddVmToVpcDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddVmToVpcDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vmId': json['vm_id'],
        'vpcId': json['vpc_id'],
    };
}

  export function AddVmToVpcDtoToJSON(json: any): AddVmToVpcDto {
      return AddVmToVpcDtoToJSONTyped(json, false);
  }

  export function AddVmToVpcDtoToJSONTyped(value?: AddVmToVpcDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vm_id': value['vmId'],
        'vpc_id': value['vpcId'],
    };
}

