/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HostnameDomainEntity
 */
export interface HostnameDomainEntity {
    /**
     * 
     * @type {number}
     * @memberof HostnameDomainEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof HostnameDomainEntity
     */
    domain: string;
    /**
     * 
     * @type {Date}
     * @memberof HostnameDomainEntity
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof HostnameDomainEntity
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the HostnameDomainEntity interface.
 */
export function instanceOfHostnameDomainEntity(value: object): value is HostnameDomainEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function HostnameDomainEntityFromJSON(json: any): HostnameDomainEntity {
    return HostnameDomainEntityFromJSONTyped(json, false);
}

export function HostnameDomainEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): HostnameDomainEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'domain': json['domain'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function HostnameDomainEntityToJSON(json: any): HostnameDomainEntity {
      return HostnameDomainEntityToJSONTyped(json, false);
  }

  export function HostnameDomainEntityToJSONTyped(value?: HostnameDomainEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'domain': value['domain'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

