/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IpEntity
 */
export interface IpEntity {
    /**
     * 
     * @type {number}
     * @memberof IpEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IpEntity
     */
    ipAddress: string;
    /**
     * 
     * @type {string}
     * @memberof IpEntity
     */
    macAddress: string;
    /**
     * 
     * @type {number}
     * @memberof IpEntity
     */
    isPublic: number;
    /**
     * 
     * @type {number}
     * @memberof IpEntity
     */
    ipPoolId: number;
    /**
     * 
     * @type {Date}
     * @memberof IpEntity
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof IpEntity
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof IpEntity
     */
    subnetId: number;
}

/**
 * Check if a given object implements the IpEntity interface.
 */
export function instanceOfIpEntity(value: object): value is IpEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ipAddress' in value) || value['ipAddress'] === undefined) return false;
    if (!('macAddress' in value) || value['macAddress'] === undefined) return false;
    if (!('isPublic' in value) || value['isPublic'] === undefined) return false;
    if (!('ipPoolId' in value) || value['ipPoolId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('subnetId' in value) || value['subnetId'] === undefined) return false;
    return true;
}

export function IpEntityFromJSON(json: any): IpEntity {
    return IpEntityFromJSONTyped(json, false);
}

export function IpEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): IpEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ipAddress': json['ip_address'],
        'macAddress': json['mac_address'],
        'isPublic': json['is_public'],
        'ipPoolId': json['ip_pool_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'subnetId': json['subnet_id'],
    };
}

  export function IpEntityToJSON(json: any): IpEntity {
      return IpEntityToJSONTyped(json, false);
  }

  export function IpEntityToJSONTyped(value?: IpEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ip_address': value['ipAddress'],
        'mac_address': value['macAddress'],
        'is_public': value['isPublic'],
        'ip_pool_id': value['ipPoolId'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'subnet_id': value['subnetId'],
    };
}

