/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ipv6Entity
 */
export interface Ipv6Entity {
    /**
     * 
     * @type {number}
     * @memberof Ipv6Entity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Ipv6Entity
     */
    ipv6Address: string;
    /**
     * 
     * @type {number}
     * @memberof Ipv6Entity
     */
    ipv6SubnetId: number;
    /**
     * 
     * @type {Date}
     * @memberof Ipv6Entity
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ipv6Entity
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ipv6Entity
     */
    deletedAt: Date;
}

/**
 * Check if a given object implements the Ipv6Entity interface.
 */
export function instanceOfIpv6Entity(value: object): value is Ipv6Entity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ipv6Address' in value) || value['ipv6Address'] === undefined) return false;
    if (!('ipv6SubnetId' in value) || value['ipv6SubnetId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    return true;
}

export function Ipv6EntityFromJSON(json: any): Ipv6Entity {
    return Ipv6EntityFromJSONTyped(json, false);
}

export function Ipv6EntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ipv6Entity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'ipv6Address': json['ipv6_address'],
        'ipv6SubnetId': json['ipv6_subnet_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'deletedAt': (new Date(json['deleted_at'])),
    };
}

  export function Ipv6EntityToJSON(json: any): Ipv6Entity {
      return Ipv6EntityToJSONTyped(json, false);
  }

  export function Ipv6EntityToJSONTyped(value?: Ipv6Entity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'ipv6_address': value['ipv6Address'],
        'ipv6_subnet_id': value['ipv6SubnetId'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'deleted_at': ((value['deletedAt']).toISOString()),
    };
}

