/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProxmoxDto
 */
export interface ProxmoxDto {
    /**
     * 
     * @type {number}
     * @memberof ProxmoxDto
     */
    proxmoxVmId: number;
    /**
     * 
     * @type {number}
     * @memberof ProxmoxDto
     */
    vmId: number;
}

/**
 * Check if a given object implements the ProxmoxDto interface.
 */
export function instanceOfProxmoxDto(value: object): value is ProxmoxDto {
    if (!('proxmoxVmId' in value) || value['proxmoxVmId'] === undefined) return false;
    if (!('vmId' in value) || value['vmId'] === undefined) return false;
    return true;
}

export function ProxmoxDtoFromJSON(json: any): ProxmoxDto {
    return ProxmoxDtoFromJSONTyped(json, false);
}

export function ProxmoxDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxmoxDto {
    if (json == null) {
        return json;
    }
    return {
        
        'proxmoxVmId': json['proxmox_vm_id'],
        'vmId': json['vm_id'],
    };
}

  export function ProxmoxDtoToJSON(json: any): ProxmoxDto {
      return ProxmoxDtoToJSONTyped(json, false);
  }

  export function ProxmoxDtoToJSONTyped(value?: ProxmoxDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'proxmox_vm_id': value['proxmoxVmId'],
        'vm_id': value['vmId'],
    };
}

