/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupFloatingIpDto
 */
export interface SetupFloatingIpDto {
    /**
     * 
     * @type {number}
     * @memberof SetupFloatingIpDto
     */
    vmId: number;
}

/**
 * Check if a given object implements the SetupFloatingIpDto interface.
 */
export function instanceOfSetupFloatingIpDto(value: object): value is SetupFloatingIpDto {
    if (!('vmId' in value) || value['vmId'] === undefined) return false;
    return true;
}

export function SetupFloatingIpDtoFromJSON(json: any): SetupFloatingIpDto {
    return SetupFloatingIpDtoFromJSONTyped(json, false);
}

export function SetupFloatingIpDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupFloatingIpDto {
    if (json == null) {
        return json;
    }
    return {
        
        'vmId': json['vm_id'],
    };
}

  export function SetupFloatingIpDtoToJSON(json: any): SetupFloatingIpDto {
      return SetupFloatingIpDtoToJSONTyped(json, false);
  }

  export function SetupFloatingIpDtoToJSONTyped(value?: SetupFloatingIpDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vm_id': value['vmId'],
    };
}

