/* tslint:disable */
/* eslint-disable */
/**
 * Master da Web API
 * The Master da Web API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VpcCreateDto
 */
export interface VpcCreateDto {
    /**
     * The name of the VPC
     * @type {string}
     * @memberof VpcCreateDto
     */
    name: string;
    /**
     * The description of the VPC
     * @type {string}
     * @memberof VpcCreateDto
     */
    description?: string;
    /**
     * The DHCP subnet of the VPC
     * @type {string}
     * @memberof VpcCreateDto
     */
    dhcpSubnet?: string;
    /**
     * The ID of the cluster
     * @type {number}
     * @memberof VpcCreateDto
     */
    clusterId: number;
}

/**
 * Check if a given object implements the VpcCreateDto interface.
 */
export function instanceOfVpcCreateDto(value: object): value is VpcCreateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('clusterId' in value) || value['clusterId'] === undefined) return false;
    return true;
}

export function VpcCreateDtoFromJSON(json: any): VpcCreateDto {
    return VpcCreateDtoFromJSONTyped(json, false);
}

export function VpcCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VpcCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'dhcpSubnet': json['dhcp_subnet'] == null ? undefined : json['dhcp_subnet'],
        'clusterId': json['cluster_id'],
    };
}

  export function VpcCreateDtoToJSON(json: any): VpcCreateDto {
      return VpcCreateDtoToJSONTyped(json, false);
  }

  export function VpcCreateDtoToJSONTyped(value?: VpcCreateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'dhcp_subnet': value['dhcpSubnet'],
        'cluster_id': value['clusterId'],
    };
}

